### ISSUE TITLE
Unresponsive on Android emulator.

### ISSUE THREAD

**Issue by cawfree** [browniefed/react-native-scrub#1]
Hey @browniefed, great work on this component! It looks awesome.

I'm having some trouble getting it to respond to touch within the Android emulator. I just wanted to run this past you to see whether this is a known issue, and it'll actually work on a physical device.

If this sounds like a genuine issue, I'll happily look into it.

#### Configuration
Running the unmodified `/example` directory against [`0.2.0`](https://github.com/browniefed/react-native-scrub/commit/b304b8cfd597031d64170416671ec4258ad1b155).

Using Qemu @ Nexus 5X API 29 x86.

Thanks!

**Comment by browniefed** [comment]
I actually do not know. I don't recall pulling it up on android at all but definitely should.
I don't see why it would be effected by any of that.

I think the only thing is that gesture handler doesn't work in RN Modals on Android. So if you're putting it in a Modal on Android yeah it won't respond https://github.com/software-mansion/react-native-gesture-handler/issues/139

**Comment by cawfree** [comment]
Thanks for the quick response.

No it's neither, just the direct example. But that's cool, I'll run it on a physical device on Monday and do some tinkering.

**Comment by browniefed** [comment]
I will do some testing later. 
I actually am using this in work code so I will need to verify Android is okay.

**Comment by cawfree** [comment]
Oh, cool! Well thanks very much for that. I'll be using this in work too, so I don't mind pitching in if you want. 👍 

Have a good weekend!
